 server.port=8081

spring.profiles.active=dev

# H2 in-memory database (for demo)
spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver
spring.h2.console.enabled=true

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

spring.sql.init.mode=never
spring.main.banner-mode=off

google.client-id=${GOOGLE_CLIENT_ID:1079704717727-3c0hitge9b5sniqh619lassoc0pd9262.apps.googleusercontent.com}
